version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin1234
      POSTGRES_DB: mysys
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: joey.cm.lam@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"